-- Full MUJ club list for Team Access, billboards, and event scheduling dropdowns.
insert into public.clubs (name, slug, short_name, description)
values
  ('Accelerate', 'accelerate', 'Accelerate', 'Accelerate club.'),
  ('AIML COMMUNITY', 'aiml-community', 'AIML', 'AIML COMMUNITY club.'),
  ('Aperture muj', 'aperture', 'Aperture', 'Aperture muj club.'),
  ('CACTUS – The Fashion & Perception Club', 'cactus-fashion-perception', 'CACTUS', 'CACTUS – The Fashion & Perception Club club.'),
  ('Cinefilia-The Dramatics and Filmmaking Club of MUJ', 'cinefilia', 'Cinefilia', 'Cinefilia-The Dramatics and Filmmaking Club of MUJ club.'),
  ('COSMOS - The Science Club', 'cosmos-science-club', 'COSMOS', 'COSMOS - The Science Club club.'),
  ('cyber space club', 'cyber-space-club', 'Cyber Space', 'cyber space club club.'),
  ('Data Science', 'data-science', 'Data Science', 'Data Science club.'),
  ('De Artistry Club', 'd-artistry', 'De Artistry', 'De Artistry Club club.'),
  ('Dept of Electrical Engineering', 'dept-electrical-engineering', 'Electrical Engg', 'Dept of Electrical Engineering club.'),
  ('Dept of Mechatronics X IEI', 'dept-mechatronics-x-iei', 'Mechatronics X IEI', 'Dept of Mechatronics X IEI club.'),
  ('Earth Club', 'earth-club', 'Earth Club', 'Earth Club club.'),
  ('eis', 'eis', 'EIS', 'eis club.'),
  ('Enactus', 'enactus', 'Enactus', 'Enactus club.'),
  ('Entrepreneur and Innovation Society', 'entrepreneur-innovation-society', 'EIS', 'Entrepreneur and Innovation Society club.'),
  ('fashion dept x d club', 'fashion-dept-x-d-club', 'Fashion X D', 'fashion dept x d club club.'),
  ('Finance Club', 'finance-club', 'Finance', 'Finance Club club.'),
  ('Garuda Club', 'garuda', 'Garuda', 'Garuda Club club.'),
  ('GLITCH! Esports Society', 'glitch-esports-society', 'GLITCH', 'GLITCH! Esports Society club.'),
  ('GNF', 'gnf', 'GNF', 'GNF club.'),
  ('GNF (Centaurus Arena Club)', 'gnf-centaurus-arena-club', 'GNF Centaurus', 'GNF (Centaurus Arena Club) club.'),
  ('Gram Asha', 'gram-asha', 'Gram Asha', 'Gram Asha club.'),
  ('Green horizon', 'green-horizon', 'Green Horizon', 'Green horizon club.'),
  ('Her Campus at MUJ', 'her-campus-at-muj', 'Her Campus', 'Her Campus at MUJ club.'),
  ('Hotel Management Dept X Epicurean', 'hotel-management-dept-x-epicurean', 'HM X Epicurean', 'Hotel Management Dept X Epicurean club.'),
  ('IEEE CIS', 'ieee-cis', 'IEEE CIS', 'IEEE CIS club.'),
  ('IEEE MTT-S, IEEE APS and IEEE AESS', 'ieee-mtt-s-aps-aess', 'IEEE MTT/APS/AESS', 'IEEE MTT-S, IEEE APS and IEEE AESS club.'),
  ('IEEE RAS SBC', 'ieee-ras', 'IEEE RAS SBC', 'IEEE RAS SBC club.'),
  ('IEEE SB MUJ', 'ieee-sb', 'IEEE SB MUJ', 'IEEE SB MUJ club.'),
  ('IEEE WIE MUJ', 'ieee-wie', 'IEEE WIE MUJ', 'IEEE WIE MUJ club.'),
  ('IEI Civil Engineering', 'iei-civil-engineering', 'IEI Civil', 'IEI Civil Engineering club.'),
  ('IEI MECHATRONICS STUDENTS'' CHAPTER', 'iei-mechatronics-students-chapter', 'IEI Mechatronics', 'IEI MECHATRONICS STUDENTS'' CHAPTER club.'),
  ('IEI Student Chapter', 'iei-student-chapter', 'IEI', 'IEI Student Chapter club.'),
  ('internantional relation club', 'international-relation-club', 'IRC', 'internantional relation club club.'),
  ('ISA MUJ Chapter', 'isa-muj-chapter', 'ISA MUJ', 'ISA MUJ Chapter club.'),
  ('LAW', 'law', 'LAW', 'LAW club.'),
  ('LearnIT MUJ', 'learnit-muj', 'LearnIT', 'LearnIT MUJ club.'),
  ('litmus', 'litmus', 'Litmus', 'litmus club.'),
  ('Managia', 'managia', 'Managia', 'Managia club.'),
  ('MarkSoc', 'marksoc', 'MarkSoc', 'MarkSoc club.'),
  ('MASDC', 'masdc', 'MASDC', 'MASDC club.'),
  ('mind over matter', 'mind-over-matter', 'Mind Over Matter', 'mind over matter club.'),
  ('MUJ ACM SIGAI Student Chapter', 'muj-acm-sigai-student-chapter', 'ACM SIGAI', 'MUJ ACM SIGAI Student Chapter club.'),
  ('MUJ ACM SIGBED Student Chapter', 'muj-acm-sigbed-student-chapter', 'ACM SIGBED', 'MUJ ACM SIGBED Student Chapter club.'),
  ('MUJ ACM STUDENT CHAPTER', 'acm', 'ACM', 'MUJ ACM STUDENT CHAPTER club.'),
  ('MUJ ACM Student Chapter x MUJ ACM SIGAI', 'muj-acm-x-sigai', 'ACM x SIGAI', 'MUJ ACM Student Chapter x MUJ ACM SIGAI club.'),
  ('Nexus', 'nexus', 'Nexus', 'Nexus club.'),
  ('olympism', 'olympism', 'Olympism', 'olympism club.'),
  ('Omphalos', 'omphalos', 'Omphalos', 'Omphalos club.'),
  ('Pitchers Craft', 'pitchers-craft', 'Pitchers Craft', 'Pitchers Craft club.'),
  ('Pitchers Craft x EIS', 'pitchers-craft-x-eis', 'Pitchers X EIS', 'Pitchers Craft x EIS club.'),
  ('Randomize();', 'randomize', 'Randomize', 'Randomize(); club.'),
  ('RPM', 'rpm', 'RPM', 'RPM club.'),
  ('Scribbles', 'scribbles', 'Scribbles', 'Scribbles club.'),
  ('SHABD chapter 2026-2027', 'shabd-chapter-2026-2027', 'SHABD', 'SHABD chapter 2026-2027 club.'),
  ('The Cypher Club', 'the-cypher-club', 'Cypher', 'The Cypher Club club.'),
  ('TMC', 'tmc', 'TMC', 'TMC club.')
on conflict (slug) do update
set
  name = excluded.name,
  short_name = excluded.short_name,
  description = excluded.description,
  updated_at = now();
